import type { Lang } from '@genoffice/i18n'

/** Labels for the queued-messages strip above the AI composer (all editors share them). */
export interface AiQueueStripLabels {
  /** collapsed strip title, e.g. "3 queued" */
  queuedCount: (n: number) => string
  clearTitle: string
  editTitle: string
  removeTitle: string
  /** hold the queue: the run in flight finishes, nothing after it starts */
  pauseTitle: string
  /** let the queue run again */
  resumeTitle: string
  /** strip hint while the gate is closed */
  pausedHint: string
  /** row tooltip: press and drag to change the order (Alt+arrows for keyboards) */
  moveTitle: string
  /** composer placeholder while a reply runs and Enter queues instead of sending */
  queuePlaceholder: string
}

export const AI_QUEUE_LABELS: Record<Lang, AiQueueStripLabels> = {
  zh: {
    queuedCount: (n) => `${n} 条排队中`,
    clearTitle: '清空排队消息',
    editTitle: '编辑排队消息',
    removeTitle: '移除排队消息',
    pauseTitle: '暂停排队',
    resumeTitle: '继续排队',
    pausedHint: '已暂停',
    moveTitle: '拖动调整顺序（或 Alt+↑/↓）',
    queuePlaceholder: 'Enter 排队 · Esc 停止',
  },
  en: {
    queuedCount: (n) => `${n} queued`,
    clearTitle: 'Clear queued messages',
    editTitle: 'Edit queued message',
    removeTitle: 'Remove queued message',
    pauseTitle: 'Pause the queue',
    resumeTitle: 'Resume the queue',
    pausedHint: 'Paused',
    moveTitle: 'Drag to reorder (or Alt+↑/↓)',
    queuePlaceholder: 'Enter to queue · Esc to stop',
  },
  ja: {
    queuedCount: (n) => `${n} 件が待機中`,
    clearTitle: '待機中のメッセージを削除',
    editTitle: '待機中のメッセージを編集',
    removeTitle: '待機中のメッセージを取り除く',
    pauseTitle: '待機を一時停止',
    resumeTitle: '待機を再開',
    pausedHint: '一時停止中',
    moveTitle: 'ドラッグで並べ替え（または Alt+↑/↓）',
    queuePlaceholder: 'Enter で待機 · Esc で停止',
  },
  ko: {
    queuedCount: (n) => `${n}개 대기 중`,
    clearTitle: '대기 중인 메시지 비우기',
    editTitle: '대기 중인 메시지 편집',
    removeTitle: '대기 중인 메시지 제거',
    pauseTitle: '대기 일시 정지',
    resumeTitle: '대기 재개',
    pausedHint: '일시 정지됨',
    moveTitle: '끌어서 순서 변경 (또는 Alt+↑/↓)',
    queuePlaceholder: 'Enter 대기 · Esc 중지',
  },
  fr: {
    queuedCount: (n) => `${n} en attente`,
    clearTitle: 'Vider les messages en attente',
    editTitle: 'Modifier le message en attente',
    removeTitle: 'Retirer le message en attente',
    pauseTitle: 'Suspendre la file',
    resumeTitle: 'Reprendre la file',
    pausedHint: 'En pause',
    moveTitle: 'Glisser pour réorganiser (ou Alt+↑/↓)',
    queuePlaceholder: 'Entrée pour mettre en attente · Échap pour arrêter',
  },
  de: {
    queuedCount: (n) => `${n} in Warteschlange`,
    clearTitle: 'Warteschlange leeren',
    editTitle: 'Nachricht in Warteschlange bearbeiten',
    removeTitle: 'Nachricht aus Warteschlange entfernen',
    pauseTitle: 'Warteschlange anhalten',
    resumeTitle: 'Warteschlange fortsetzen',
    pausedHint: 'Angehalten',
    moveTitle: 'Zum Sortieren ziehen (oder Alt+↑/↓)',
    queuePlaceholder: 'Enter zum Einreihen · Esc zum Stoppen',
  },
  es: {
    queuedCount: (n) => `${n} en cola`,
    clearTitle: 'Vaciar mensajes en cola',
    editTitle: 'Editar mensaje en cola',
    removeTitle: 'Quitar mensaje en cola',
    pauseTitle: 'Pausar la cola',
    resumeTitle: 'Reanudar la cola',
    pausedHint: 'En pausa',
    moveTitle: 'Arrastra para reordenar (o Alt+↑/↓)',
    queuePlaceholder: 'Entrada para encolar · Esc para detener',
  },
  th: {
    queuedCount: (n) => `กำลังรออยู่ ${n} รายการ`,
    clearTitle: 'ล้างข้อความที่รออยู่',
    editTitle: 'แก้ไขข้อความที่รออยู่',
    removeTitle: 'นำข้อความที่รออยู่ออก',
    pauseTitle: 'หยุดคิวชั่วคราว',
    resumeTitle: 'ดำเนินคิวต่อ',
    pausedHint: 'หยุดชั่วคราว',
    moveTitle: 'ลากเพื่อจัดลำดับใหม่ (หรือ Alt+↑/↓)',
    queuePlaceholder: 'Enter เพื่อจัดคิว · Esc เพื่อหยุด',
  },
  id: {
    queuedCount: (n) => `${n} dalam antrean`,
    clearTitle: 'Kosongkan pesan yang mengantre',
    editTitle: 'Edit pesan yang mengantre',
    removeTitle: 'Hapus pesan yang mengantre',
    pauseTitle: 'Jeda antrean',
    resumeTitle: 'Lanjutkan antrean',
    pausedHint: 'Dijeda',
    moveTitle: 'Geser untuk mengubah urutan (atau Alt+↑/↓)',
    queuePlaceholder: 'Enter untuk mengantre · Esc untuk berhenti',
  },
  ru: {
    queuedCount: (n) => `${n} в очереди`,
    clearTitle: 'Очистить очередь сообщений',
    editTitle: 'Изменить сообщение в очереди',
    removeTitle: 'Убрать сообщение из очереди',
    pauseTitle: 'Приостановить очередь',
    resumeTitle: 'Возобновить очередь',
    pausedHint: 'Приостановлено',
    moveTitle: 'Перетащите, чтобы изменить порядок (или Alt+↑/↓)',
    queuePlaceholder: 'Enter — в очередь · Esc — остановить',
  },
  ar: {
    queuedCount: (n) => `${n} في قائمة الانتظار`,
    clearTitle: 'إفراغ الرسائل المنتظرة',
    editTitle: 'تعديل الرسالة المنتظرة',
    removeTitle: 'إزالة الرسالة المنتظرة',
    pauseTitle: 'إيقاف الانتظار مؤقتًا',
    resumeTitle: 'متابعة الانتظار',
    pausedHint: 'موقوف مؤقتًا',
    moveTitle: 'اسحب لإعادة الترتيب (أو Alt+↑/↓)',
    queuePlaceholder: 'Enter للانتظار · Esc للإيقاف',
  },
  pt: {
    queuedCount: (n) => `${n} na fila`,
    clearTitle: 'Limpar mensagens na fila',
    editTitle: 'Editar mensagem na fila',
    removeTitle: 'Remover mensagem da fila',
    pauseTitle: 'Pausar a fila',
    resumeTitle: 'Retomar a fila',
    pausedHint: 'Em pausa',
    moveTitle: 'Arraste para reordenar (ou Alt+↑/↓)',
    queuePlaceholder: 'Enter para enfileirar · Esc para parar',
  },
  it: {
    queuedCount: (n) => `${n} in coda`,
    clearTitle: 'Svuota i messaggi in coda',
    editTitle: 'Modifica il messaggio in coda',
    removeTitle: 'Rimuovi il messaggio in coda',
    pauseTitle: 'Metti in pausa la coda',
    resumeTitle: 'Riprendi la coda',
    pausedHint: 'In pausa',
    moveTitle: 'Trascina per riordinare (o Alt+↑/↓)',
    queuePlaceholder: 'Invio per accodare · Esc per fermare',
  },
  pl: {
    queuedCount: (n) => `${n} w kolejce`,
    clearTitle: 'Wyczyść wiadomości w kolejce',
    editTitle: 'Edytuj wiadomość w kolejce',
    removeTitle: 'Usuń wiadomość z kolejki',
    pauseTitle: 'Wstrzymaj kolejkę',
    resumeTitle: 'Wznów kolejkę',
    pausedHint: 'Wstrzymana',
    moveTitle: 'Przeciągnij, aby zmienić kolejność (lub Alt+↑/↓)',
    queuePlaceholder: 'Enter, aby zakolejkować · Esc, aby zatrzymać',
  },
  cs: {
    queuedCount: (n) => `${n} ve frontě`,
    clearTitle: 'Vymazat zprávy ve frontě',
    editTitle: 'Upravit zprávu ve frontě',
    removeTitle: 'Odebrat zprávu z fronty',
    pauseTitle: 'Pozastavit frontu',
    resumeTitle: 'Obnovit frontu',
    pausedHint: 'Pozastaveno',
    moveTitle: 'Přetáhněte pro změnu pořadí (nebo Alt+↑/↓)',
    queuePlaceholder: 'Enter zařadí · Esc zastaví',
  },
  nl: {
    queuedCount: (n) => `${n} in wachtrij`,
    clearTitle: 'Wachtrij leegmaken',
    editTitle: 'Bericht in wachtrij bewerken',
    removeTitle: 'Bericht uit wachtrij verwijderen',
    pauseTitle: 'Wachtrij pauzeren',
    resumeTitle: 'Wachtrij hervatten',
    pausedHint: 'Gepauzeerd',
    moveTitle: 'Sleep om te herschikken (of Alt+↑/↓)',
    queuePlaceholder: 'Enter om te wachtrijken · Esc om te stoppen',
  },
  ms: {
    queuedCount: (n) => `${n} dalam baris gilir`,
    clearTitle: 'Kosongkan mesej dalam baris gilir',
    editTitle: 'Edit mesej dalam baris gilir',
    removeTitle: 'Buang mesej dalam baris gilir',
    pauseTitle: 'Jeda barisan',
    resumeTitle: 'Sambung barisan',
    pausedHint: 'Dijeda',
    moveTitle: 'Seret untuk susun semula (atau Alt+↑/↓)',
    queuePlaceholder: 'Enter untuk baris gilir · Esc untuk berhenti',
  },
  he: {
    queuedCount: (n) => `${n} בתור`,
    clearTitle: 'נקה הודעות בתור',
    editTitle: 'ערוך הודעה בתור',
    removeTitle: 'הסר הודעה מהתור',
    pauseTitle: 'השהה את התור',
    resumeTitle: 'חדש את התור',
    pausedHint: 'מושהה',
    moveTitle: 'גרור כדי לסדר מחדש (או Alt+↑/↓)',
    queuePlaceholder: 'Enter לתור · Esc לעצירה',
  },
  hi: {
    queuedCount: (n) => `${n} कतार में`,
    clearTitle: 'कतार में संदेश साफ़ करें',
    editTitle: 'कतार में संदेश संपादित करें',
    removeTitle: 'कतार में संदेश हटाएँ',
    pauseTitle: 'कतार रोकें',
    resumeTitle: 'कतार फिर शुरू करें',
    pausedHint: 'रोका गया',
    moveTitle: 'क्रम बदलने के लिए खींचें (या Alt+↑/↓)',
    queuePlaceholder: 'कतार के लिए Enter · रोकने के लिए Esc',
  },
  'zh-TW': {
    queuedCount: (n) => `${n} 則排隊中`,
    clearTitle: '清空排隊訊息',
    editTitle: '編輯排隊訊息',
    removeTitle: '移除排隊訊息',
    pauseTitle: '暫停排隊',
    resumeTitle: '繼續排隊',
    pausedHint: '已暫停',
    moveTitle: '拖曳調整順序（或 Alt+↑/↓）',
    queuePlaceholder: 'Enter 排隊 · Esc 停止',
  },
  vi: {
    queuedCount: (n) => `${n} đang chờ`,
    clearTitle: 'Xoá các tin nhắn đang chờ',
    editTitle: 'Sửa tin nhắn đang chờ',
    removeTitle: 'Bỏ tin nhắn đang chờ',
    pauseTitle: 'Tạm dừng hàng đợi',
    resumeTitle: 'Tiếp tục hàng đợi',
    pausedHint: 'Đã tạm dừng',
    moveTitle: 'Kéo để đổi thứ tự (hoặc Alt+↑/↓)',
    queuePlaceholder: 'Enter để xếp hàng · Esc để dừng',
  },
}
