#!/usr/bin/env python3
"""Regenerates aof-footage-log-example.docx: a sample AI footage log whose
[Watch] links use the aof-review:// scheme (see docs/src/shared/link-protocols.ts).
Run from this directory: python3 make-aof-footage-log-example.py
"""
import zipfile
from xml.sax.saxutils import escape

CLIPS = [
    ("A001_C002_0812.mov", "00:00:14:03", "Wide establishing shot, kitchen set, dolly settles"),
    ("A001_C002_0812.mov", "00:01:12:05", "Chef intro sound bite: \"fire is the first ingredient\""),
    ("A002_C007_0812.mxf", "00:03:44:12", "Overhead plating insert, steam catches the backlight"),
    ("B001_C001_0812.braw", "00:00:52:00", "B-cam reaction, host laughs, usable cutaway"),
]
FOLDER = "/Volumes/RAID/AOF/ShootDay_0812"


def link(url: str, rid: str, text: str) -> str:
    return (
        f'<w:hyperlink r:id="{rid}">'
        f'<w:r><w:rPr><w:rStyle w:val="Hyperlink"/></w:rPr>'
        f"<w:t>{escape(text)}</w:t></w:r></w:hyperlink>"
    )


def para(inner: str) -> str:
    return f"<w:p>{inner}</w:p>"


def run(text: str, bold: bool = False) -> str:
    rpr = "<w:rPr><w:b/></w:rPr>" if bold else ""
    return f'<w:r>{rpr}<w:t xml:space="preserve">{escape(text)}</w:t></w:r>'


def aof_url(path: str, tc: str) -> str:
    from urllib.parse import quote
    return f"aof-review://seek?file={quote(path, safe='')}&tc={quote(tc, safe='')}&play=1"


rels, body = [], []
body.append(para(run("AOF Footage Log — Shoot Day 2026-08-12", bold=True)))
body.append(para(run("Generated by the aof-footage-log skill. Cmd+Click a [Watch] link to jump to the frame in AOF Footage Review.")))
rid_n = 100
folder_url = f"aof-review://open?folder={__import__('urllib.parse', fromlist=['quote']).quote(FOLDER, safe='')}"
rels.append((f"rId{rid_n}", folder_url))
body.append(para(run("Project folder: ") + link(folder_url, f"rId{rid_n}", FOLDER)))
for fname, tc, note in CLIPS:
    rid_n += 1
    url = aof_url(f"{FOLDER}/{fname}", tc)
    rels.append((f"rId{rid_n}", url))
    body.append(para(run(f"{fname}  {tc}  — {note}  ", bold=False) + link(url, f"rId{rid_n}", "[Watch]")))

document = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
    'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
    f"<w:body>{''.join(body)}</w:body></w:document>"
)

rel_items = "".join(
    f'<Relationship Id="{rid}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="{escape(url)}" TargetMode="External"/>'
    for rid, url in rels
)
document_rels = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
    f"{rel_items}</Relationships>"
)
root_rels = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
    '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>'
    "</Relationships>"
)
content_types = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
    '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
    '<Default Extension="xml" ContentType="application/xml"/>'
    '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
    "</Types>"
)

with zipfile.ZipFile("aof-footage-log-example.docx", "w", zipfile.ZIP_DEFLATED) as z:
    z.writestr("[Content_Types].xml", content_types)
    z.writestr("_rels/.rels", root_rels)
    z.writestr("word/document.xml", document)
    z.writestr("word/_rels/document.xml.rels", document_rels)
print("wrote aof-footage-log-example.docx")
